---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: check code version
      ansible.builtin.command:
        cmd: "code --version --false-sandbox --user-data-dir=/tmp"
      register: code_version

    - name: check returned version
      debug: var=code_version.stdout
